#!/bin/sh
set -e

# Generate Secrets.swift from Xcode Cloud environment variables

REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$CI_WORKSPACE}"
SECRETS_DIR="$REPO_ROOT/OG Bike Computer/Services/Integrations"
SECRETS_PATH="$SECRETS_DIR/Secrets.swift"

mkdir -p "$SECRETS_DIR"

cat > "$SECRETS_PATH" << EOF
//
//  Secrets.swift
//  OG Bike Computer
//
//  Generated by Xcode Cloud — do not edit
//

import Foundation

// MARK: - Strava

struct StravaConfig {
    static let clientID = "$STRAVA_CLIENT_ID"
    static let clientSecret = "$STRAVA_CLIENT_SECRET"
    static let redirectURI = "ogbikecomputer://aidan3445.github.io"
    static let callbackScheme = "ogbikecomputer"
}

// MARK: - Ride With GPS

struct RWGPSConfig {
    static let clientID = "$RWGPS_CLIENT_ID"
    static let clientSecret = "$RWGPS_CLIENT_SECRET"
    static let apiKey = "$RWGPS_API_KEY"
    static let apiSecret = "$RWGPS_API_SECRET"
    static let redirectURI = "ogbikecomputer://aidan3445.github.io"
    static let callbackScheme = "ogbikecomputer"
}
EOF

if [ ! -f "$SECRETS_PATH" ]; then
    echo "ERROR: Failed to create Secrets.swift at $SECRETS_PATH"
    exit 1
fi

echo "Generated Secrets.swift at $SECRETS_PATH"
