#!/bin/sh

# Generate Secrets.swift from Xcode Cloud environment variables

SECRETS_PATH="$CI_WORKSPACE/OG Bike Computer/Services/Integrations/Secrets.swift"

cat > "$SECRETS_PATH" << EOF
//
//  Secrets.swift
//  OG Bike Computer
//
//  Generated by Xcode Cloud — do not edit
//

import Foundation

// MARK: - Strava

struct StravaConfig {
    static let clientID = "$STRAVA_CLIENT_ID"
    static let clientSecret = "$STRAVA_CLIENT_SECRET"
    static let redirectURI = "ogbikecomputer://aidan3445.github.io"
    static let callbackScheme = "ogbikecomputer"
}

// MARK: - Ride With GPS

struct RWGPSConfig {
    static let clientID = "$RWGPS_CLIENT_ID"
    static let clientSecret = "$RWGPS_CLIENT_SECRET"
    static let apiKey = "$RWGPS_API_KEY"
    static let apiSecret = "$RWGPS_API_SECRET"
    static let redirectURI = "ogbikecomputer://aidan3445.github.io"
    static let callbackScheme = "ogbikecomputer"
}
EOF

echo "Generated Secrets.swift at $SECRETS_PATH"
